name: Check Upstream Releases
on:
  workflow_dispatch:

jobs:
  check-asusctl:
    runs-on: ubuntu-24.04
    outputs:
      new_version: ${{ steps.check.outputs.asusctl_latest }}
      needs_update: ${{ steps.check.outputs.asusctl_needs_update }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Check GitLab releases
        id: check
        run: |
          python3 .github/scripts/check_gitlab_release.py
      
      - name: Trigger bottle build if new
        if: steps.check.outputs.asusctl_needs_update == 'true'
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          event-type: build-asusctl-bottle
          client-payload: '{"version": "${{ steps.check.outputs.asusctl_latest }}"}'